// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"DM/internal/biz"
	"DM/internal/conf"
	"DM/internal/data"
	"DM/internal/server"
	"DM/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	departmentRepo := data.NewDepartmentRepository(dataData)
	departmentUC := biz.NewDepartmentUC(departmentRepo)
	departmentService := service.NewDepartmentService(departmentUC)
	subDepartmentRepo := data.NewSubDepartmentRepository(dataData)
	subDepartmentUC := biz.NewSubDepartmentUC(subDepartmentRepo)
	subDepartmentService := service.NewSubDepartmentService(subDepartmentUC)
	employeeRepo := data.NewEmployeeRepository(dataData)
	employeeUC := biz.NewEmployeeUC(employeeRepo)
	employeeService := service.NewEmployeeService(employeeUC)
	userRepository := data.NewUserRepository(dataData)
	userUC := biz.NewUserUC(userRepository, employeeRepo)
	userService := service.NewUserService(userUC)
	grpcServer := server.NewGRPCServer(confServer, departmentService, subDepartmentService, employeeService, userService, logger)
	httpServer := server.NewHTTPServer(confServer, departmentService, subDepartmentService, employeeService, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
